const std = @import("std");
const node = @import("node.zig");
const GeneralContext = @import("GeneralContext.zig");
const ty = @import("type.zig");
const TypeRef = @import("type_ref.zig").TypeRef;

const Io = std.Io;

const CBackend = @This();

const indent_size = 4;

ctx: *GeneralContext,
indent_level: u16 = 0,
type_store: *ty.Store,

// oof all of these store the same allocator :(, what a waste!
// in particular that is 16 bytes each, so we are wasting 48 bytes
_pre: Io.Writer.Allocating,
_decls: Io.Writer.Allocating,
_impls: Io.Writer.Allocating,

pub fn init(ctx: *GeneralContext, type_store: *ty.Store) CBackend {
    return .{
        .ctx = ctx,
        .type_store = type_store,
        ._pre = .init(ctx.allocator),
        ._decls = .init(ctx.allocator),
        ._impls = .init(ctx.allocator),
    };
}

pub fn deinit(b: *CBackend) void {
    b._pre.deinit();
    b._decls.deinit();
    b._impls.deinit();
}

pub fn enterSourceFile(b: *CBackend, _: *node.SourceFile) !void {
    b.generate(b.pre(),
        \\// generated by iorac
        \\
        \\#include <stdint.h>
        \\
        \\typedef struct {
        \\    char *data;
        \\    uint64_t len;
        \\} str;
    );
}

pub fn exitSourceFile(b: *CBackend, _: *node.SourceFile) !void {
    try b.pre().flush();
    try b.decls().flush();
    try b.impls().flush();
}

pub fn enterVarDecl(b: *CBackend, var_decl: *node.VarDecl) void {
    var stream = b.impls();
    if (b.indent_level == 0) {
        stream = b.decls();
    }
    // Globals go with fwd decls
    b.generatef(stream,
        \\
        \\{f} {s};
    , .{
        b.ctype(var_decl.type_ref),
        var_decl.name.text(),
    });
}

pub fn enterFunDecl(b: *CBackend, fun_decl: *node.FunDecl) void {
    const modifier = if (fun_decl.linkage == .external) "extern" else "";
    b.generatef(b.decls(),
        \\
        \\{s} {f} {s}(
    , .{
        modifier,
        b.ctype(b.type_store.get(fun_decl.type_ref).fun.signature.get(b.type_store.*).return_type),
        fun_decl.name.text(),
    });
    for (fun_decl.params, 0..) |param, i| {
        if (i != 0) {
            b.generateNoIndent(b.decls(), ", ");
        }
        b.generateNoIndentf(b.decls(), "{f} {s}", .{ b.ctype(param.type_ref), param.name.text() });
    }
    b.generateNoIndent(b.decls(), ");");
}

pub fn enterCompStmt(b: *CBackend, _: *node.CompStmt) void {
    b.generate(b.impls(),
        \\
        \\{
    );
    b.indent();
}

pub fn exitCompStmt(b: *CBackend, _: *node.CompStmt) void {
    b.dedent();
    b.generate(b.impls(),
        \\
        \\}
    );
}

pub fn generateNoIndent(_: *CBackend, stream: *Io.Writer, code: []const u8) void {
    stream.writeAll(code) catch @panic("OOM");
}

pub fn generate(b: *CBackend, stream: *Io.Writer, code: []const u8) void {
    var tmp = Io.Writer.Allocating.init(b.ctx.scratch.allocator());
    defer _ = b.ctx.scratch.reset(.retain_capacity);

    tmp.writer.writeAll(code) catch @panic("OOM");
    tmp.writer.flush() catch @panic("OOM");

    b.generateWithIndent(stream, tmp.written());
}

pub fn generateNoIndentf(_: *CBackend, stream: *Io.Writer, comptime fmt: []const u8, args: anytype) void {
    stream.print(fmt, args) catch @panic("OOM");
}

pub fn generatef(b: *CBackend, stream: *Io.Writer, comptime fmt: []const u8, args: anytype) void {
    var tmp = Io.Writer.Allocating.init(b.ctx.scratch.allocator());
    defer _ = b.ctx.scratch.reset(.retain_capacity);

    tmp.writer.print(fmt, args) catch @panic("OOM");
    tmp.writer.flush() catch @panic("OOM");

    b.generateWithIndent(stream, tmp.written());
}

fn generateWithIndent(b: *CBackend, stream: *Io.Writer, code: []const u8) void {
    var it = std.mem.splitScalar(u8, code, '\n');
    var i: usize = 0;
    while (it.next()) |line| : (i += 1) {
        if (i != 0) {
            stream.writeByte('\n') catch @panic("OOM");
        }
        const lead_ws = stream.writableSlice(b.indent_level * indent_size) catch @panic("OOM");
        @memset(lead_ws, ' ');
        stream.writeAll(line) catch @panic("OOM");
    }
}

pub fn emit(b: *CBackend, to: *Io.Writer) !void {
    try to.writeAll(b._pre.written());
    if (b._decls.written().len != 0) {
        try to.writeByte('\n');
        try to.writeAll(b._decls.written());
    }
    if (b._impls.written().len != 0) {
        try to.writeByte('\n');
        try to.writeAll(b._impls.written());
    }
}

const CType = struct {
    b: *CBackend,
    ref: TypeRef,

    pub fn format(
        ct: CType,
        writer: *Io.Writer,
    ) Io.Writer.Error!void {
        if (switch (ct.ref) {
            .u8 => "uint8_t",
            .s8 => "int8_t",
            .u16 => "uint16_t",
            .s16 => "int16_t",
            .u32 => "uint32_t",
            .s32 => "int32_t",
            .u64 => "uint64_t",
            .s64 => "int64_t",
            .f32 => "float",
            .f64 => "double",
            .str => "str",
            .unit => "void",
            else => null,
        }) |builtin_type| {
            try writer.writeAll(builtin_type);
            return;
        }
        var td = ct.b.type_store.get(ct.ref);
        if (td != .ptr) {
            switch (td) {
                .user => |user| {
                    try writer.writeAll(user.name.text());
                    return;
                },
                else => unreachable,
            }
        } else {
            while (td == .ptr) {
                try ct.b.ctype(td.ptr).format(writer);
                try writer.writeByte('*');
                td = ct.b.type_store.get(td.ptr);
            }
        }
    }
};

fn ctype(b: *CBackend, tr: TypeRef) CType {
    return .{
        .b = b,
        .ref = tr,
    };
}

fn indent(b: *CBackend) void {
    b.indent_level += 1;
}

fn dedent(b: *CBackend) void {
    b.indent_level -= 1;
}

inline fn pre(b: *CBackend) *Io.Writer {
    return &b._pre.writer;
}
inline fn decls(b: *CBackend) *Io.Writer {
    return &b._decls.writer;
}
inline fn impls(b: *CBackend) *Io.Writer {
    return &b._impls.writer;
}
